# Generated by Django 4.2.7 on 2024-01-09 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_supplier', '0005_alter_order_expirate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 9, 13, 53)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='expirate_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 17, 41, 24, 516520)),
        ),
    ]
