# Generated by Django 4.2.7 on 2024-01-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
