# Generated by Django 4.2.7 on 2024-01-05 19:14

import _dashboard.models.SupplierService
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboard', '0003_alter_unity_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierservice',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='supplierservice',
            name='warranty',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='_dashboard.category'),
        ),
        migrations.AlterField(
            model_name='supplierservice',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=_dashboard.models.SupplierService.supplier_service_image_path),
        ),
    ]
