# Generated by Django 4.2.7 on 2024-01-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboard', '0004_remove_supplierservice_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='_dashboard.category'),
        ),
        migrations.AlterField(
            model_name='supplierservice',
            name='service',
            field=models.ForeignKey(limit_choices_to={'id': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_dashboard.service'),
        ),
    ]
