# Generated by Django 4.2.7 on 2024-01-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboard', '0005_alter_category_parent_alter_supplierservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-09 13:53:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierservice',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_dashboard.service'),
        ),
    ]
