# Generated by Django 4.2.7 on 2024-01-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboard', '0006_supplierservice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='_dashboard.service'),
        ),
    ]
