# Generated by Django 4.2.7 on 2024-01-13 03:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0002_alter_screen_created_on_alter_supplier_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='name_owner',
            new_name='owner_name',
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 0, 46, 17, 586894)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Informe um telefone válido.', regex='^[(]\\d{2}[)] \\d{5}[-]\\d{4}$')]),
        ),
    ]
