# Generated by Django 4.2.7 on 2024-01-30 00:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0002_userauth_is_active_userauth_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 21, 14, 16, 215413)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user_auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 21, 14, 16, 313440)),
        ),
    ]
