# Generated by Django 4.2.7 on 2024-01-13 13:57

import _web.models.supplier.supplier_model
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0003_rename_name_owner_supplier_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 10, 57, 17, 462487)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_document_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='owner_document_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=_web.models.supplier.supplier_model.Supplier.image_path),
        ),
    ]
