# Generated by Django 4.2.7 on 2024-01-30 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0003_alter_screen_created_on_alter_supplier_user_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 13, 24, 12, 922292)),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 13, 24, 13, 23294)),
        ),
    ]
