# Generated by Django 4.2.7 on 2024-01-13 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0004_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='paragraph',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 13, 28, 0, 883628)),
        ),
    ]
