# Generated by Django 5.0.2 on 2024-03-02 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0005_supplier_user_auth_user_user_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 18, 4, 43, 800096)),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 18, 4, 43, 950703)),
        ),
    ]
