# Generated by Django 4.2.7 on 2024-01-13 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0005_screen_paragraph_screen_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 13, 29, 19, 864585)),
        ),
        migrations.AlterField(
            model_name='screen',
            name='paragraph',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
