# Generated by Django 4.2.7 on 2024-01-31 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0005_user_name_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 13, 33, 52, 122626)),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 13, 33, 52, 249620)),
        ),
    ]
