# Generated by Django 4.2.7 on 2024-01-14 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0006_alter_screen_created_on_alter_screen_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_name_show',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 18, 6, 34, 959992)),
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=200, null=True)),
                ('neighborhood', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_web.supplier')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
