# Generated by Django 4.2.7 on 2024-01-15 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0007_supplier_company_name_show_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_phone',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 23, 1, 42, 374872)),
        ),
    ]
