# Generated by Django 4.2.7 on 2024-02-14 01:04

import _web.models.supplier.details_model
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0008_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierdetails',
            name='company_phone',
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 22, 4, 40, 40603)),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='company_document_number',
            field=models.CharField(max_length=19, validators=[_web.models.supplier.details_model.SupplierDetails.company_document_is_valid]),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 22, 4, 40, 136602)),
        ),
    ]
