# Generated by Django 4.2.7 on 2024-02-14 01:36

import _web.models.supplier.details_model
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0009_remove_supplierdetails_company_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 22, 36, 36, 781626)),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='owner_document_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[_web.models.supplier.details_model.SupplierDetails.company_document_is_valid]),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 22, 36, 36, 877456)),
        ),
    ]
