# Generated by Django 4.2.7 on 2024-01-15 18:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0009_alter_screen_created_on_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 15, 58, 49, 299662)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='owner_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Informe um telefone válido.', regex='^[(]\\d{2}[)] \\d{5}[-]\\d{4}$')]),
        ),
    ]
