# Generated by Django 4.2.7 on 2024-02-14 02:36

import _web.models.supplier.details_model
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0010_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetails',
            name='cnd',
            field=models.FileField(blank=True, null=True, upload_to=_web.models.supplier.details_model.SupplierDetails.cnd_path),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='term',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 23, 36, 13, 362122)),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 23, 36, 13, 465123)),
        ),
    ]
