# Generated by Django 4.2.7 on 2024-01-15 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0010_alter_screen_created_on_alter_supplier_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='password',
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 16, 40, 8, 528993)),
        ),
    ]
