# Generated by Django 4.2.7 on 2024-01-16 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0011_remove_supplier_password_alter_screen_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='owner_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 21, 4, 24, 456846)),
        ),
    ]
