# Generated by Django 4.2.7 on 2024-02-15 03:04

import _web.models.supplier.details_model
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0011_supplierdetails_cnd_supplierdetails_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 0, 4, 50, 65248)),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='cnd',
            field=models.FileField(blank=True, null=True, upload_to=_web.models.supplier.details_model.SupplierDetails.cnd_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=_web.models.supplier.details_model.SupplierDetails.image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 0, 4, 50, 243231)),
        ),
    ]
