# Generated by Django 4.2.7 on 2024-01-16 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0012_supplier_owner_birthdate_alter_screen_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='owner_birthdate',
            new_name='professional_birthdate',
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 21, 5, 2, 912082)),
        ),
    ]
