# Generated by Django 4.2.7 on 2024-02-17 01:42

import _web.models.supplier.details_model
import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0019_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetails',
            name='sign_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 22, 40, 43, 156780)),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='cnd',
            field=models.FileField(default='supplier/id/cnd/namefile', upload_to=_web.models.supplier.details_model.SupplierDetails.cnd_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='photo',
            field=models.ImageField(default='supplier/id/photo_profile/namefile', upload_to=_web.models.supplier.details_model.SupplierDetails.image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 22, 40, 43, 252611)),
        ),
    ]
