# Generated by Django 4.2.7 on 2024-02-17 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0020_supplierdetails_sign_at_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 22, 48, 0, 691745)),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='term',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 22, 48, 0, 809565)),
        ),
    ]
