# Generated by Django 4.2.7 on 2024-02-17 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0012_team_created_at_team_updated_at_worker_created_at_and_more'),
        ('_web', '0021_alter_screen_created_on_alter_supplierdetails_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetails',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='_panel.category'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 15, 23, 2, 927979)),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 15, 23, 3, 45979)),
        ),
    ]
