# Generated by Django 4.2.7 on 2024-02-19 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0038_state_alter_screen_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='ibge_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='ibge_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 17, 19, 40, 541806)),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 17, 19, 40, 636831)),
        ),
    ]
