# Generated by Django 4.2.7 on 2024-01-29 22:41

import _panel.models.service.category_model
import _panel.models.service.service_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=_panel.models.service.category_model.Category.image_path)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GeneralService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'general_service',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to=_panel.models.service.service_model.Service.supplier_service_image_path)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('execution_time', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('general_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_panel.generalservice')),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
