# Generated by Django 4.2.7 on 2024-01-29 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_web', '0001_initial'),
        ('_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_web.supplier'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='_panel.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='_panel.category'),
        ),
    ]
