# Generated by Django 5.0.2 on 2024-03-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_panel', '0001_initial'),
        ('_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='_web.supplier'),
        ),
        migrations.AddField(
            model_name='team',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='_web.supplier'),
        ),
        migrations.AddField(
            model_name='service',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='_panel.team'),
        ),
        migrations.AddField(
            model_name='unitforservice',
            name='general_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_for_service', to='_panel.generalservice'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_for_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='_panel.unitforservice'),
        ),
        migrations.AddField(
            model_name='worker',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='_panel.team'),
        ),
        migrations.AddField(
            model_name='service',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='services', to='_panel.worker'),
        ),
    ]
