# Generated by Django 4.2.7 on 2024-01-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0004_alter_screen_created_on_and_more'),
        ('_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='_web.supplier'),
        ),
    ]
