# Generated by Django 5.0.2 on 2024-03-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
    ]
