# Generated by Django 4.2.7 on 2024-02-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0012_alter_screen_created_on_alter_supplierdetails_cnd_and_more'),
        ('_panel', '0004_alter_service_general_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='_web.supplier')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='_panel.team')),
            ],
            options={
                'db_table': 'worker',
            },
        ),
    ]
