# Generated by Django 4.2.7 on 2024-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0006_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
