# Generated by Django 4.2.7 on 2024-02-15 18:07

import _panel.models.team.team_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0007_alter_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=_panel.models.team.team_model.Team.team_image_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
