# Generated by Django 4.2.7 on 2024-02-15 22:29

import _panel.models.team.worker_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0008_team_photo_alter_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, upload_to=_panel.models.team.worker_model.Worker.worker_image_path),
        ),
    ]
