# Generated by Django 4.2.7 on 2024-02-15 22:41

import _panel.models.team.worker_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0009_alter_worker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='document',
            field=models.CharField(default=None, max_length=20, validators=[_panel.models.team.worker_model.Worker.company_document_is_valid]),
            preserve_default=False,
        ),
    ]
