# Generated by Django 4.2.7 on 2024-02-15 22:55

import _panel.models.team.worker_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0010_worker_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='employment_date',
            field=models.DateField(validators=[_panel.models.team.worker_model.Worker.date_is_valid]),
        ),
    ]
