# Generated by Django 4.2.7 on 2024-02-18 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0013_rename_unit_service_unit_for_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitForPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('general_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_for_price', to='_panel.generalservice')),
            ],
            options={
                'db_table': 'unit_for_price',
            },
        ),
    ]
