# Generated by Django 4.2.7 on 2024-02-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0014_unitforprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='unit_for_price',
            new_name='unit_for_service',
        ),
    ]
