# Generated by Django 4.2.7 on 2024-02-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0015_rename_unit_for_price_service_unit_for_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitForPrice',
            new_name='UnitForService',
        ),
        migrations.AlterModelTable(
            name='unitforservice',
            table='unit_for_service',
        ),
    ]
