# Generated by Django 4.2.7 on 2024-02-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0016_rename_unitforprice_unitforservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitforservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unitforservice',
            name='updated_at',
        ),
    ]
