# Generated by Django 4.2.7 on 2024-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0017_remove_unitforservice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('general_service', models.ManyToManyField(related_name='units_for_execution', to='_panel.generalservice')),
            ],
            options={
                'db_table': 'unit_of_execution',
            },
        ),
    ]
