# Generated by Django 4.2.7 on 2024-02-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0018_unitofexecution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitOfExecution',
        ),
    ]
