# Generated by Django 4.2.7 on 2024-02-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0020_rename_unit_for_execution_service_unit_of_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_for_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_unit', to='_panel.unitforservice'),
        ),
        migrations.AlterField(
            model_name='unitforservice',
            name='general_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_for_service', to='_panel.generalservice'),
        ),
    ]
