# Generated by Django 4.2.7 on 2024-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0021_alter_service_unit_for_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_for_service',
            field=models.CharField(max_length=50),
        ),
    ]
