# Generated by Django 4.2.7 on 2024-02-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0022_alter_service_unit_for_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_for_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='_panel.unitforservice'),
        ),
    ]
