# Generated by Django 4.2.7 on 2024-02-19 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_panel', '0023_alter_service_unit_for_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='execution_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
