from .category.all_categories_serializer import AllCategorySerializer
from .category.segment_serializer import SegmentSerializer
from .category.categories_serializer import CategoriesSerializer


from .service.general_services_serializer import GeneralServiceSerializer
from .service.services_serializer import ServiceSerializer


from .supplier.supplier_serializer import SupplierSerializer
from .supplier.details_serializer import DetailsSerializer
from .supplier.address_serializer import AddressSerializer